### ISSUE TITLE
Enums don't show up anymore

### ISSUE THREAD

**Issue by zatherz** [Kapiainen/The-Subliming-Of-Isaac#10]
![spectacle m15420](https://cloud.githubusercontent.com/assets/4568670/24331629/7fb69f60-1238-11e7-9a53-1037c6629578.png)

**Comment by Kapiainen** [comment]
Looks like the API documentation has been updated. I tried to scrape it and the size of the produced JSON file went down from 668 KB to 459 KB. Seems like the documentation isn't being parsed correctly at the moment. I'll look into fixing this.

**Comment by Kapiainen** [comment]
[Should be fixed in version 1.5.1](https://github.com/Kapiainen/The-Subliming-Of-Isaac/releases). The file containing the enum documentation had been renamed, which caused the API scraper to fail to find the old file. Just install the new version, scrape the API again, and you should be good to go.

**Comment by zatherz** [comment]
Lovely. Thanks.
