### ISSUE TITLE
Dictionaries over multiple lines gives error

### ISSUE THREAD

**Issue by Leblarh** [Kapiainen/The-Subliming-Of-Isaac#8]
When writing a dictionary that stretches multiple lines it returns an error, stating
> expected right curly brace, got newline instead

The problem can be recreated by the following dictionary:
```lua
local Bonus = {
    Damage = 0.4,
    Speed = 0.3
}
```
I have tested it in Isaac with ```Isaac.RenderText(Bonus.Damage, 120, 50, 1.0, 0.0, 0.0, 1)```and it works completely fine.

**Comment by Kapiainen** [comment]
Give the latest beta version a try. It should fix the issue.
